#%RAML 0.8
title: API Using media type in the URL
baseUri: message://event/listener/message/other
version: v1
/other.event:
  post:
    body:
        application/vnd.example.cake-made+json:
            schema: !include json/schema/example.cake-made.json
            example: !include json/make-cake.json
